name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload bot files
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          uploads: |
            ./ => /
          ignore: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            **/.env
            **/.gitignore
            **/README.md
